### ISSUE TITLE
Cannot place static html page in Sphinx template

### ISSUE THREAD

**Issue by johnsBeharry** [premAI-io/state-of-open-source-ai#63]
Hey Team,

As you know, we've been trying to incorporate a custom `index.html` page in our [Jupyter Book/Sphinx] book that does not adhere to the standard theme and I've hit a roadblock. 

### Challenge
After exploring various options, it appears that Jupyter Book and Sphinx are not designed to easily allow a completely custom `index.html` that diverges from the set themes so the https://premai-book.netlify.app seems unusable at this point.

### Proposed Solution
The fastest way to implement our custom `index.html` seems to be post-build where we'd:

1. Run the standard Jupyter Book or Sphinx build command to generate the documentation.
2. Execute a post-build script to replace the default `index.html` with our custom version.

### Next Steps
- I wouldn't want to break anything with the current site so would need someone to help with this script

**Comment by johnsBeharry** [comment]
Sent as a Zip file to not pollute the git history

**Comment by Janaka-Steph** [comment]
You don't pollute history with a PR
